spring.application.name=customer-manager

#Server
spring.webflux.base-path=/customer
server.port=9090

#R2DBC Connection
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/customers
spring.r2dbc.username=admin
spring.r2dbc.password=debuggeandoideas

#R2DBC Pool Connection
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=15
spring.r2dbc.pool.max-size=30
spring.r2dbc.pool.max-life-time=180000ms
spring.r2dbc.pool.max-idle-time=100000ms
spring.r2dbc.pool.max-create-connection-time=10000ms
spring.r2dbc.pool.validation-query=SELECT 1
spring.r2dbc.pool.validation-depth=local

#R2DBC Logging
logging.level.org.springframework.data.r2dbc=INFO
logging.level.io.r2dbc.pool=INFO
logging.level.org.springframework.transaction=INFO





